name: prototips
favicon: null
layout_spectrum: 0.4119744396302849
typography_spectrum: 0.039566379273310304
title: Advanced UX Prototyping Tricks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.10513283335603774
  lightness: 0.8285528342239559
  saturation: 0.16449703881517053
  rhythmicContrast: 0.9521611023228616
purpose: []
